name: app_nation_case_study
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #State Management
  flutter_bloc: ^8.1.3

  #Utils
  dartz: ^0.10.1
  get_it: ^7.6.4
  equatable: ^2.0.5

  #Network
  dio: ^5.3.4

  #UI
  flutter_svg: ^2.0.9

  #Navigation
  go_router: ^12.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: GalanoGrotesque
      fonts:
        - asset: assets/fonts/galano_grotesque/GalanoGrotesque-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/galano_grotesque/GalanoGrotesque-Light.ttf
          weight: 300
        - asset: assets/fonts/galano_grotesque/GalanoGrotesque-Regular.ttf
          weight: 400
        - asset: assets/fonts/galano_grotesque/GalanoGrotesque-Medium.ttf
          weight: 500
        - asset: assets/fonts/galano_grotesque/GalanoGrotesque-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/galano_grotesque/GalanoGrotesque-Bold.ttf
          weight: 700
        - asset: assets/fonts/galano_grotesque/GalanoGrotesque-ExtraBold.ttf
          weight: 800
